export default {
    "host":{
        "url":"http://localhost",
        "port":"5000"
    },
    "mail":{
        "host":"smtp.gmail.com",
        "port":587,
        "secure":false,
        "auth":{
            "user":"testnestjs122@gmail.com",
            "password":"MEMNxk8VJXdZ'"
        },
        "from":"testnestjs122@gmail.com"
    },
    "jwt":{
        "secretOrKey":"secret",
        "expiresIn":36000000
    }
}
